# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.base:
        class: ArchBundle\Services\Base\BaseGenerationService
    app.structure:
            class: ArchBundle\Services\Structure\StructureHelperService
    app.unit:
            class: ArchBundle\Services\Unit\UnitHelperService
    app.fight:
            class: ArchBundle\Services\Fight\FightService
    app.viewHelper:
          class: ArchBundle\Services\View\ViewHelper
    services:
          class: ArchBundle\Services\ServiceHolder
          arguments: ['@app.viewHelper','@app.base','@app.structure','@app.unit','@app.fight']